import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

export const RUNTIME_EXEC_POLICY_FILE = "runtime-action-firewall.rules";

export const RUNTIME_EXEC_POLICY = `# Generated by Agent Trust Gateway. Do not edit from an Agent workspace.
# These rules are evaluated by Codex before model-generated shell commands execute.

prefix_rule(pattern = ["npm", "test"], decision = "allow")
prefix_rule(pattern = ["npm", "run", "test"], decision = "allow")
prefix_rule(pattern = ["npm", "run", "build"], decision = "allow")
prefix_rule(pattern = ["git", "status"], decision = "allow")
prefix_rule(pattern = ["git", "diff"], decision = "allow")

prefix_rule(pattern = ["rm", "-rf"], decision = "forbidden", justification = "Recursive forced deletion is blocked by the Runtime Action Firewall.")
prefix_rule(pattern = ["rm", "-fr"], decision = "forbidden", justification = "Recursive forced deletion is blocked by the Runtime Action Firewall.")
prefix_rule(pattern = ["sudo"], decision = "forbidden", justification = "Privilege escalation is blocked by the Runtime Action Firewall.")
prefix_rule(pattern = ["chmod", "777"], decision = "forbidden", justification = "World-writable permissions are blocked by the Runtime Action Firewall.")
prefix_rule(pattern = ["curl"], decision = "forbidden", justification = "Direct network clients are blocked by the Runtime Action Firewall.")
prefix_rule(pattern = ["wget"], decision = "forbidden", justification = "Direct network clients are blocked by the Runtime Action Firewall.")
prefix_rule(pattern = ["ssh"], decision = "forbidden", justification = "Remote shell access is blocked by the Runtime Action Firewall.")
prefix_rule(pattern = ["docker", "run"], decision = "forbidden", justification = "Nested container execution is blocked by the Runtime Action Firewall.")
prefix_rule(pattern = ["git", "push"], decision = "forbidden", justification = "Remote repository writes are blocked by the Runtime Action Firewall.")
`;

export async function writeRuntimeExecPolicy(codexHome: string): Promise<string> {
  const policyDirectory = path.join(codexHome, "execpolicy");
  await mkdir(policyDirectory, { recursive: true });
  const policyPath = path.join(policyDirectory, RUNTIME_EXEC_POLICY_FILE);
  await writeFile(policyPath, RUNTIME_EXEC_POLICY, { encoding: "utf8", mode: 0o600 });
  return policyPath;
}
