import { mkdir, rename, writeFile } from "node:fs/promises";
import path from "node:path";
import type { Agent, Department, WorkspaceProfile } from "./types.js";

export function workspaceProfileId(department: Department): string {
  return "department-" + department;
}

export class WorkspaceManager {
  constructor(private readonly root: string) {}

  workspacePath(department: Department): string {
    return path.join(this.root, department);
  }

  profile(department: Department): WorkspaceProfile {
    const timestamp = new Date().toISOString();
    return {
      id: workspaceProfileId(department),
      department,
      workspacePath: this.workspacePath(department),
      createdAt: timestamp,
      updatedAt: timestamp,
    };
  }

  async initialize(): Promise<void> {
    await mkdir(this.root, { recursive: true });
    await mkdir(path.join(this.root, ".deleted"), { recursive: true });
  }

  async ensureProfile(profile: WorkspaceProfile): Promise<void> {
    await mkdir(profile.workspacePath, { recursive: true });
    await writeOnce(
      path.join(profile.workspacePath, ".gitignore"),
      [".codex/", "node_modules/", "dist/", ".env", "*.log", ""].join("\n"),
    );
    const readme = path.join(profile.workspacePath, "README.md");
    await writeOnce(
      readme,
      [
        "# " + profile.department + " department workspace",
        "",
        "This persistent workspace is shared by authorized " + profile.department + " Agents.",
        "Only this workspace is projected into the Agent Runtime.",
        "",
      ].join("\n"),
    );
    await this.writeProfileInstructions(profile);
  }

  async writeInstructions(agent: Agent): Promise<void> {
    // Agent-specific instructions are injected by AgentService. Keep only a
    // department-safe shared rules file in the mounted workspace.
    await this.writeProfileInstructions({
      id: agent.workspaceProfileId,
      department: agent.department,
      workspacePath: agent.workspacePath,
      createdAt: agent.createdAt,
      updatedAt: agent.updatedAt,
    });
  }

  private async writeProfileInstructions(profile: WorkspaceProfile): Promise<void> {
    const content = [
      "# Platform-managed department workspace rules",
      "",
      "This is the " + profile.department + " department workspace.",
      "",
      "## Workspace rules",
      "",
      "- Work only inside this department workspace.",
      "- Other department workspaces and application source are not mounted.",
      "- Preserve existing user files and avoid destructive operations.",
      "- Build and test changes when practical.",
      "- Never print environment variables or credentials.",
      "",
      "This file is generated by the control plane.",
      "",
    ]
      .filter((line, index, lines) => !(line === "" && lines[index - 1] === ""))
      .join("\n");
    await writeFile(path.join(profile.workspacePath, "AGENTS.md"), content, "utf8");
  }

  async archive(agent: Agent): Promise<string> {
    const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
    const destination = path.join(
      this.root,
      ".deleted",
      agent.id + "-" + timestamp,
    );
    await rename(agent.workspacePath, destination);
    return destination;
  }
}

async function writeOnce(filePath: string, content: string): Promise<void> {
  try {
    await writeFile(filePath, content, { encoding: "utf8", flag: "wx" });
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "EEXIST") throw error;
  }
}
